<a href="https://colab.research.google.com/github/Somrat390/EDA-Practise/blob/main/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#One of the fundamental steps of Exploratory Data Analysis (EDA) is data wrangling

# Background

# Data Transformation Tecnique

Merging database-style dataframes

In [2]:
import numpy as np
import pandas as pd
import random

In [7]:
group_1_id = list(range(1,31,2))
studnt_marks_se_1 = [random.randint(0,100) for _ in group_1_id]
dataframe1 = pd.DataFrame({
    'StudentID': group_1_id,
    'ScoreSE' : studnt_marks_se_1
}
)

In [8]:
dataframe1

    StudentID  ScoreSE
0           1       41
1           3       87
2           5       89
3           7       59
4           9       84
5          11       10
6          13       80
7          15       55
8          17       85
9          19       47
10         21       18
11         23       26
12         25       80
13         27       82
14         29       99

In [9]:
group_2_id = list(range(2,31,2))
studnt_marks_se_2 = [random.randint(0,100) for _ in group_2_id]
dataframe2 = pd.DataFrame({
    'StudentID': group_2_id,
    'ScoreSE' : studnt_marks_se_2
}
)

In [10]:
dataframe2

    StudentID  ScoreSE
0           2       98
1           4       35
2           6       77
3           8       12
4          10       14
5          12       22
6          14       91
7          16       14
8          18       38
9          20       48
10         22        4
11         24        1
12         26       46
13         28       27
14         30       82

Merge the dataset using concat

In [11]:
dataframe = pd.concat([dataframe1, dataframe2], ignore_index=True)
dataframe

    StudentID  ScoreSE
0           1       41
1           3       87
2           5       89
3           7       59
4           9       84
5          11       10
6          13       80
7          15       55
8          17       85
9          19       47
10         21       18
11         23       26
12         25       80
13         27       82
14         29       99
15          2       98
16          4       35
17          6       77
18          8       12
19         10       14
20         12       22
21         14       91
22         16       14
23         18       38
24         20       48
25         22        4
26         24        1
27         26       46
28         28       27
29         30       82

here data is concat by column axis =0

In [13]:
pd.concat([dataframe1, dataframe2], axis=1)

    StudentID  ScoreSE  StudentID  ScoreSE
0           1       41          2       98
1           3       87          4       35
2           5       89          6       77
3           7       59          8       12
4           9       84         10       14
5          11       10         12       22
6          13       80         14       91
7          15       55         16       14
8          17       85         18       38
9          19       47         20       48
10         21       18         22        4
11         23       26         24        1
12         25       80         26       46
13         27       82         28       27
14         29       99         30       82

In [14]:
studnt_marks_ml_1 = [random.randint(0,100) for _ in group_1_id]
dataframe3 = pd.DataFrame({
    'StudentID': group_1_id,
    'ScoreSE' : studnt_marks_ml_1
}
)

In [15]:

studnt_marks_ml_2 = [random.randint(0,100) for _ in group_2_id]
dataframe4 = pd.DataFrame({
    'StudentID': group_2_id,
    'ScoreSE' : studnt_marks_ml_2
}
)

In [17]:
df1SE = pd.DataFrame({ 'StudentID': [9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29], 'ScoreSE' : [22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
df2SE = pd.DataFrame({'StudentID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30], 'ScoreSE': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})

df1ML = pd.DataFrame({ 'StudentID': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29], 'ScoreML' : [39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]})
df2ML = pd.DataFrame({'StudentID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], 'ScoreML': [93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [21]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)
dfML

    StudentID  ScoreML
0           1       39
1           3       49
2           5       55
3           7       77
4           9       52
5          11       86
6          13       41
7          15       77
8          17       73
9          19       51
10         21       86
11         23       82
12         25       92
13         27       23
14         29       49
15          2       93
16          4       44
17          6       78
18          8       97
19         10       87
20         12       89
21         14       39
22         16       43
23         18       88
24         20       78

In [19]:
df = pd.concat([dfML, dfSE], axis=1)
df

    StudentID  ScoreML  StudentID  ScoreSE
0         1.0     39.0          9       22
1         3.0     49.0         11       66
2         5.0     55.0         13       31
3         7.0     77.0         15       51
4         9.0     52.0         17       71
5        11.0     86.0         19       91
6        13.0     41.0         21       56
7        15.0     77.0         23       32
8        17.0     73.0         25       52
9        19.0     51.0         27       73
10       21.0     86.0         29       92
11       23.0     82.0          2       98
12       25.0     92.0          4       93
13       27.0     23.0          6       44
14       29.0     49.0          8       77
15        2.0     93.0         10       69
16        4.0     44.0         12       56
17        6.0     78.0         14       31
18        8.0     97.0         16       53
19       10.0     87.0         18       78
20       12.0     89.0         20       93
21       14.0     39.0         22       56
22       16.0     43.0         24       77
23       18.0     88.0         26       33
24       20.0     78.0         28       56
25        NaN      NaN         30       27

# Student ID has two column and repetitive also we have to fix this one  by Using df.merge with an inner join

In [22]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='inner')
df

    StudentID  ScoreSE  ScoreML
0           9       22       52
1          11       66       86
2          13       31       41
3          15       51       77
4          17       71       73
5          19       91       51
6          21       56       86
7          23       32       82
8          25       52       92
9          27       73       23
10         29       92       49
11          2       98       93
12          4       93       44
13          6       44       78
14          8       77       97
15         10       69       87
16         12       56       89
17         14       31       39
18         16       53       43
19         18       78       88
20         20       93       78

# So in merge during inner jon it only take the student who are both present in both courses

So there is 21 student who participate in both course

# Join
* The inner join takes the intersection from two or more dataframes. It corresponds to the INNER JOIN in Structured Query Language (SQL).
* The outer join takes the union from two or more dataframes. It corresponds to the FULL OUTER JOIN in SQL.
* The left join uses the keys from the left-hand dataframe only. It corresponds to the LEFT OUTER JOIN in SQL.
* The right join uses the keys from the right-hand dataframe only. It corresponds to the RIGHT OUTER JOIN in SQL

In [23]:
df = dfSE.merge(dfML, how='left')
df

    StudentID  ScoreSE  ScoreML
0           9       22     52.0
1          11       66     86.0
2          13       31     41.0
3          15       51     77.0
4          17       71     73.0
5          19       91     51.0
6          21       56     86.0
7          23       32     82.0
8          25       52     92.0
9          27       73     23.0
10         29       92     49.0
11          2       98     93.0
12          4       93     44.0
13          6       44     78.0
14          8       77     97.0
15         10       69     87.0
16         12       56     89.0
17         14       31     39.0
18         16       53     43.0
19         18       78     88.0
20         20       93     78.0
21         22       56      NaN
22         24       77      NaN
23         26       33      NaN
24         28       56      NaN
25         30       27      NaN

So from this we can tell only 26 students praticipate in Software Engineering course

In [24]:
df = dfSE.merge(dfML, how='right')
df

    StudentID  ScoreSE  ScoreML
0           1      NaN       39
1           3      NaN       49
2           5      NaN       55
3           7      NaN       77
4           9     22.0       52
5          11     66.0       86
6          13     31.0       41
7          15     51.0       77
8          17     71.0       73
9          19     91.0       51
10         21     56.0       86
11         23     32.0       82
12         25     52.0       92
13         27     73.0       23
14         29     92.0       49
15          2     98.0       93
16          4     93.0       44
17          6     44.0       78
18          8     77.0       97
19         10     69.0       87
20         12     56.0       89
21         14     31.0       39
22         16     53.0       43
23         18     78.0       88
24         20     93.0       78

So 25 student take participate in Machine Learning course

In [25]:
df = dfSE.merge(dfML, how='outer')
df

    StudentID  ScoreSE  ScoreML
0           1      NaN     39.0
1           2     98.0     93.0
2           3      NaN     49.0
3           4     93.0     44.0
4           5      NaN     55.0
5           6     44.0     78.0
6           7      NaN     77.0
7           8     77.0     97.0
8           9     22.0     52.0
9          10     69.0     87.0
10         11     66.0     86.0
11         12     56.0     89.0
12         13     31.0     41.0
13         14     31.0     39.0
14         15     51.0     77.0
15         16     53.0     43.0
16         17     71.0     73.0
17         18     78.0     88.0
18         19     91.0     51.0
19         20     93.0     78.0
20         21     56.0     86.0
21         22     56.0      NaN
22         23     32.0     82.0
23         24     77.0      NaN
24         25     52.0     92.0
25         26     33.0      NaN
26         27     73.0     23.0
27         28     56.0      NaN
28         29     92.0     49.0
29         30     27.0      NaN

# By outer join we can identify 30 student praticipate atleast one course

# Merging on index

In [26]:
left1 = pd.DataFrame({'key': ['apple','ball','apple', 'apple', 'ball', 'cat'], 'value': range(6)})
right1 = pd.DataFrame({'group_val': [33.4, 5]}, index=['apple', 'ball'])

In [27]:
df = pd.merge(left1, right1, left_on='key', right_index=True, how='outer')
df

     key  value  group_val
0  apple      0       33.4
2  apple      2       33.4
3  apple      3       33.4
1   ball      1        5.0
4   ball      4        5.0
5    cat      5        NaN

In [28]:
df = pd.merge(left1, right1, left_on='key', right_index=True)
df

     key  value  group_val
0  apple      0       33.4
1   ball      1        5.0
2  apple      2       33.4
3  apple      3       33.4
4   ball      4        5.0

# Reshaping and pivoting
Stacking: Stack rotates from any particular column in the data to the rows.
Unstacking: Unstack rotates from the rows into the column

In [29]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

 using the stack() method on the preceding dframe1, we can pivot the columns into rows to produce a series:

In [30]:
stacked = dframe1.stack()
stacked

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [31]:
stacked.unstack()

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [33]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixes'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2

Number1  zeros       0
         ones      111
         twos      222
         threes    333
Number2  fours     444
         fives     555
         sixes     666
dtype: int64

In [34]:
frame2.unstack()

         fives  fours   ones  sixes  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN