<a href="https://colab.research.google.com/github/Somrat390/EDA-Practise/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("employee_promotion_updated.csv")

In [ ]:
df.shape

(55808, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55808 entries, 0 to 55807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           55808 non-null  int64
 1   department            55808 non-null  object
 2   region                55808 non-null  object
 3   education             53399 non-null  object
 4   gender                55808 non-null  object
 5   recruitment_channel   55808 non-null  object
 6   no_of_trainings       55808 non-null  int64
 7   age                   55808 non-null  int64
 8   previous_year_rating  51684 non-null  float64
 9   length_of_service     55808 non-null  int64
 10  awards_won            55808 non-null  int64
 11  avg_training_score    53248 non-null  float64
 12  is_promoted           55808 non-null  int64
dtypes: float64(2), int64(6), object(5)
memory usage: 5.5+ MB

In [ ]:
df.head(3)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
0,65438,Sales & Marketing,Bangalore,Master's & above,f,sourcing,1,35,5.0,8,0,49.0,0
1,65141,Operations,Hyderabad,Bachelor's,m,other,1,30,5.0,4,0,60.0,0
2,7513,Sales & Marketing,Pune,Bachelor's,m,sourcing,1,34,3.0,7,0,50.0,0

In [ ]:
df.describe()

,employee_id,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
count,55808.000000,55808.000000,55808.000000,51684.00000,55808.000000,55808.000000,53248.000000,55808.000000
mean,39447.996846,1.310439,34.892757,3.31420,5.927788,0.058253,63.912809,0.092854
std,22733.215403,0.832126,7.775199,1.26812,4.322626,0.354155,13.612474,0.290230
min,1.000000,0.000000,20.000000,0.00000,0.000000,0.000000,39.000000,0.000000
25%,19846.500000,1.000000,29.000000,3.00000,3.000000,0.000000,51.000000,0.000000
50%,39435.500000,1.000000,33.000000,3.00000,5.000000,0.000000,60.000000,0.000000
75%,58968.500000,1.000000,39.000000,4.00000,8.000000,0.000000,77.000000,0.000000
max,99853.000000,10.000000,60.000000,5.00000,37.000000,4.000000,99.840000,1.000000

In [ ]:
df.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won                 0
avg_training_score      2560
is_promoted                0
dtype: int64

In [ ]:
missing_percentage = df.isnull().mean() * 100

print(missing_percentage)

employee_id             0.000000
department              0.000000
region                  0.000000
education               4.316585
gender                  0.000000
recruitment_channel     0.000000
no_of_trainings         0.000000
age                     0.000000
previous_year_rating    7.389622
length_of_service       0.000000
awards_won              0.000000
avg_training_score      4.587156
is_promoted             0.000000
dtype: float64

In [ ]:
df.shape

(55808, 13)

In [ ]:
df.dropna().shape

(47380, 13)

In [ ]:
df[df.duplicated()].shape

(0, 13)

In [ ]:
for col in df.columns:
  if df[col].nunique() < 20:
    print(df[col].value_counts())
    print('-'*50)

department
Sales & Marketing    17113
Operations           11593
Technology            7369
Procurement           7138
Analytics             5352
HR                    2669
Finance               2536
Legal                 1039
R&D                    999
Name: count, dtype: int64
--------------------------------------------------
education
Bachelor's          36992
Master's & above    14925
Below Secondary       805
High School           357
Master's              320
Name: count, dtype: int64
--------------------------------------------------
gender
m    38991
f    16817
Name: count, dtype: int64
--------------------------------------------------
recruitment_channel
other       30653
sourcing    23421
referred     1142
Naukri        202
Indeed        199
linkedin      191
Name: count, dtype: int64
--------------------------------------------------
no_of_trainings
1     44490
2      8089
3      1881
4       561
5       213
6       156
7       112
8       111
9        95
0        95
10        5
Name: count, dtype: int64
--------------------------------------------------
awards_won
0    53736
1     1482
2      202
4      201
3      187
Name: count, dtype: int64
--------------------------------------------------
is_promoted
0    50626
1     5182
Name: count, dtype: int64
--------------------------------------------------

# Data Cleaning

In [ ]:
df.isnull().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won                 0
avg_training_score      2560
is_promoted                0
dtype: int64

In [ ]:
df[df['avg_training_score'].isna()]

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
31,58536,Finance,Lucknow,Bachelor's,m,other,2,26,1.0,2,0,NaN,0
67,16502,Sales & Marketing,Hyderabad,Bachelor's,m,sourcing,1,27,NaN,1,0,NaN,1
128,42068,Operations,Kolkata,Master's & above,m,other,1,38,5.0,9,0,NaN,0
159,30106,Sales & Marketing,Coimbatore,Bachelor's,f,sourcing,1,32,4.0,4,0,NaN,0
166,4134,Sales & Marketing,Coimbatore,Bachelor's,f,other,1,39,1.0,8,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54701,23170,Sales & Marketing,Nagpur,Master's & above,m,other,1,39,1.0,11,0,NaN,0
54736,38707,Operations,Lucknow,Bachelor's,m,other,1,34,5.0,6,0,NaN,0
54746,10546,Finance,Dehradun,Bachelor's,m,other,1,28,NaN,1,0,NaN,0
54773,37919,Finance,Delhi,Bachelor's,m,other,1,23,NaN,1,0,NaN,0
54806,13614,Sales & Marketing,Shillong,NaN,m,sourcing,1,29,1.0,2,0,NaN,0

In [ ]:
df[df['previous_year_rating'].isna() & df['length_of_service'] > 1]

Empty DataFrame
Columns: [employee_id, department, region, education, gender, recruitment_channel, no_of_trainings, age, previous_year_rating, length_of_service, awards_won, avg_training_score, is_promoted]
Index: []

In [ ]:
df['previous_year_rating'] = df['previous_year_rating'].fillna(0)

In [ ]:
df['avg_training_score'] = df['avg_training_score'].fillna(df['avg_training_score'].median())

In [ ]:
df[df['employee_id'] == 58536]

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
31,58536,Finance,Lucknow,Bachelor's,m,other,2,26,1.0,2,0,60.0,0

In [ ]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
0,65438,Sales & Marketing,Bangalore,Master's & above,f,sourcing,1,35,5.0,8,0,49.0,0
1,65141,Operations,Hyderabad,Bachelor's,m,other,1,30,5.0,4,0,60.0,0
2,7513,Sales & Marketing,Pune,Bachelor's,m,sourcing,1,34,3.0,7,0,50.0,0
3,2542,Sales & Marketing,Chennai,Bachelor's,m,other,2,39,1.0,10,0,50.0,0
4,48945,Technology,Mumbai,Bachelor's,m,other,1,45,3.0,2,0,73.0,0

In [ ]:
df['education'].unique()

array(["Master's & above", "Bachelor's", nan, 'Below Secondary',
       "Master's", 'High School'], dtype=object)

In [ ]:
df['education'].value_counts()

education
Bachelor's          36992
Master's & above    14925
Below Secondary       805
High School           357
Master's              320
Name: count, dtype: int64

In [ ]:
df['education'] = df['education'].fillna(df['education'].mode()[0])

In [ ]:
df.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
awards_won              0
avg_training_score      0
is_promoted             0
dtype: int64

# Feature Engineering

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55808 entries, 0 to 55807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           55808 non-null  int64
 1   department            55808 non-null  object
 2   region                55808 non-null  object
 3   education             55808 non-null  object
 4   gender                55808 non-null  object
 5   recruitment_channel   55808 non-null  object
 6   no_of_trainings       55808 non-null  int64
 7   age                   55808 non-null  int64
 8   previous_year_rating  55808 non-null  float64
 9   length_of_service     55808 non-null  int64
 10  awards_won            55808 non-null  int64
 11  avg_training_score    55808 non-null  float64
 12  is_promoted           55808 non-null  int64
dtypes: float64(2), int64(6), object(5)
memory usage: 5.5+ MB

In [ ]:
df_encoded = df.copy()

In [ ]:
df['department'].value_counts()

department
Sales & Marketing    17113
Operations           11593
Technology            7369
Procurement           7138
Analytics             5352
HR                    2669
Finance               2536
Legal                 1039
R&D                    999
Name: count, dtype: int64

In [ ]:
# Frequency Encoding
department_count = df_encoded['department'].value_counts().to_dict()
df_encoded['department'] = df_encoded['department'].map(department_count)

In [ ]:
df['region'].value_counts()

region
Delhi                 12369
Hyderabad              6451
Bangalore              4873
Kochi                  2834
Chandigarh             2671
Mumbai                 2294
Lucknow                1959
Ahmedabad              1735
Patna                  1694
Coimbatore             1497
Nagpur                 1352
Indore                 1335
Chennai                1202
Jaipur                 1025
Jamshedpur              977
Pune                    910
Noida                   879
Thiruvananthapuram      857
Mysore                  845
Visakhapatnam           823
Bhubaneswar             801
Dehradun                715
Ranchi                  696
Vadodara                677
Hubli                   677
Kolkata                 638
Amritsar                537
Guwahati                533
Shillong                444
Surat                   439
Pondicherry             377
Gurgaon                 317
Raipur                  303
Shimla                   72
Name: count, dtype: int64

In [ ]:
region_count = df_encoded['region'].value_counts().to_dict()
df_encoded['region'] = df_encoded['region'].map(region_count)

In [ ]:
df['education'].value_counts()

education
Bachelor's          39401
Master's & above    14925
Below Secondary       805
High School           357
Master's              320
Name: count, dtype: int64

In [ ]:
# Label Encoding
df_encoded['education'] = df_encoded['education'].map({'High School':0, 'Below Secondary':1,"Bachelor's":2,"Master's":3,"Master's & above":4})

In [ ]:
# One-hot using dummy
df_encoded = pd.get_dummies(df_encoded, columns=['gender'], drop_first=True, dtype=int)

In [ ]:
df_encoded['recruitment_channel'].value_counts()

recruitment_channel
other       30653
sourcing    23421
referred     1142
Naukri        202
Indeed        199
linkedin      191
Name: count, dtype: int64

In [ ]:
df_encoded = pd.get_dummies(df_encoded, columns=['recruitment_channel'], drop_first=True, dtype=int)

In [ ]:
df_encoded.shape

(55808, 17)

In [ ]:
df_encoded.head()

,employee_id,department,region,education,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted,gender_m,recruitment_channel_Naukri,recruitment_channel_linkedin,recruitment_channel_other,recruitment_channel_referred,recruitment_channel_sourcing
0,65438,17113,4873,4,1,35,5.0,8,0,49.0,0,0,0,0,0,0,1
1,65141,11593,6451,2,1,30,5.0,4,0,60.0,0,1,0,0,1,0,0
2,7513,17113,910,2,1,34,3.0,7,0,50.0,0,1,0,0,0,0,1
3,2542,17113,1202,2,2,39,1.0,10,0,50.0,0,1,0,0,1,0,0
4,48945,7369,2294,2,1,45,3.0,2,0,73.0,0,1,0,0,1,0,0

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler,

In [ ]:
b